--급여 등급별 인원수 조회하기 
SELECT S.GRADE, COUNT(*)
FROM EMPLOYEES E, SALARY_GRADE S
WHERE E.SALARY >= S.MIN_SALARY AND E.SALARY <= S.MAX_SALARY
GROUP BY S.GRADE;
--이전에는 이렇게 진행했지만 이제는 
SELECT EMP_SALARY_GRADE, COUNT(*)
FROM EMP_DETAILS_VIEW
GROUP BY EMP_SALARY_GRADE; --이제 이렇게 간편하게 조회가능함

-- 년도별, 부서이름별 신규 입사자수 조회하기 
SELECT TO_CHAR(E.HIRE_DATE,'YYYY') ,D.DEPARTMENT_NAME, COUNT(*)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
GROUP BY TO_CHAR(E.HIRE_DATE,'YYYY'), D.DEPARTMENT_NAME
ORDER BY 1,2;

SELECT TO_CHAR(EMP_HIRE_DATE,'YYYY') ,EMP_DEPT_NAME, COUNT(*)
FROM EMP_DETAILS_VIEW
GROUP BY TO_CHAR(EMP_HIRE_DATE,'YYYY') ,EMP_DEPT_NAME
ORDER BY 1,2;

--급여등급이 D등급이고 Oxford에 근무하는 직원의 이름, 직종, 직종제목, 부서명을 조회하기 
SELECT E.FIRST_NAME, E.JOB_ID, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D, SALARY_GRADE S, LOCATIONS L
WHERE S.GRADE = 'D'
AND L.CITY = 'Oxford'
AND E.JOB_ID = J.JOB_ID
AND E.SALARY >= S.MIN_SALARY AND E.SALARY <= S.MAX_SALARY
AND D.LOCATION_ID = L.LOCATION_ID(+)
AND  E.EMPLOYEE_ID = D.DEPARTMENT_ID(+);
--조회가 되지 않음 그러나 뷰를 사용하면 좀더쉽고 빠르고 간단한 명령어로 추적가능하다.

SELECT EMP_NAME, EMP_JOB_ID, EMP_JOB_TITLE, EMP_DEPT_NAME
FROM EMP_DETAILS_VIEW
WHERE EMP_SALARY_GRADE = 'D' AND EMP_CITY = 'Oxford';